//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompetitivePriceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompetitivePriceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompetitivePriceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Price" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}PriceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="condition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subcondition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="belongsToRequester" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompetitivePriceType", propOrder = {
    "competitivePriceId",
    "price"
})
public class CompetitivePriceType {

    @XmlElement(name = "CompetitivePriceId", required = true)
    protected String competitivePriceId;
    @XmlElement(name = "Price", required = true)
    protected PriceType price;
    @XmlAttribute(name = "condition", required = true)
    protected String condition;
    @XmlAttribute(name = "subcondition", required = true)
    protected String subcondition;
    @XmlAttribute(name = "belongsToRequester", required = true)
    protected boolean belongsToRequester;

    /**
     * Gets the value of the competitivePriceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompetitivePriceId() {
        return competitivePriceId;
    }

    /**
     * Sets the value of the competitivePriceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompetitivePriceId(String value) {
        this.competitivePriceId = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCondition(String value) {
        this.condition = value;
    }

    /**
     * Gets the value of the subcondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubcondition() {
        return subcondition;
    }

    /**
     * Sets the value of the subcondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubcondition(String value) {
        this.subcondition = value;
    }

    /**
     * Gets the value of the belongsToRequester property.
     * 
     */
    public boolean isBelongsToRequester() {
        return belongsToRequester;
    }

    /**
     * Sets the value of the belongsToRequester property.
     * 
     */
    public void setBelongsToRequester(boolean value) {
        this.belongsToRequester = value;
    }

}
