//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompetitivePricingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompetitivePricingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CompetitivePrices" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}CompetitivePriceList"/>
 *         &lt;element name="NumberOfOfferListings" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}NumberOfOfferListingsType" minOccurs="0"/>
 *         &lt;element name="TradeInValue" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompetitivePricingType", propOrder = {
    "competitivePrices",
    "numberOfOfferListings",
    "tradeInValue"
})
public class CompetitivePricingType {

    @XmlElement(name = "CompetitivePrices", required = true)
    protected CompetitivePriceList competitivePrices;
    @XmlElement(name = "NumberOfOfferListings")
    protected NumberOfOfferListingsType numberOfOfferListings;
    @XmlElement(name = "TradeInValue")
    protected MoneyType tradeInValue;

    /**
     * Gets the value of the competitivePrices property.
     * 
     * @return
     *     possible object is
     *     {@link CompetitivePriceList }
     *     
     */
    public CompetitivePriceList getCompetitivePrices() {
        return competitivePrices;
    }

    /**
     * Sets the value of the competitivePrices property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetitivePriceList }
     *     
     */
    public void setCompetitivePrices(CompetitivePriceList value) {
        this.competitivePrices = value;
    }

    /**
     * Gets the value of the numberOfOfferListings property.
     * 
     * @return
     *     possible object is
     *     {@link NumberOfOfferListingsType }
     *     
     */
    public NumberOfOfferListingsType getNumberOfOfferListings() {
        return numberOfOfferListings;
    }

    /**
     * Sets the value of the numberOfOfferListings property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberOfOfferListingsType }
     *     
     */
    public void setNumberOfOfferListings(NumberOfOfferListingsType value) {
        this.numberOfOfferListings = value;
    }

    /**
     * Gets the value of the tradeInValue property.
     * 
     * @return
     *     possible object is
     *     {@link MoneyType }
     *     
     */
    public MoneyType getTradeInValue() {
        return tradeInValue;
    }

    /**
     * Sets the value of the tradeInValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MoneyType }
     *     
     */
    public void setTradeInValue(MoneyType value) {
        this.tradeInValue = value;
    }

}
