//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * The minimum and maximum time in hours that the
 *         item will likely be shipped once the order has been placed
 *       
 * 
 * <p>Java class for DetailedShippingTimeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DetailedShippingTimeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="minimumHours" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="maximumHours" type="{http://www.w3.org/2001/XMLSchema}short" />
 *       &lt;attribute name="availableDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="availabilityType" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}AvailabilityType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DetailedShippingTimeType")
public class DetailedShippingTimeType {

    @XmlAttribute(name = "minimumHours")
    protected Short minimumHours;
    @XmlAttribute(name = "maximumHours")
    protected Short maximumHours;
    @XmlAttribute(name = "availableDate")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar availableDate;
    @XmlAttribute(name = "availabilityType")
    protected AvailabilityType availabilityType;

    /**
     * Gets the value of the minimumHours property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMinimumHours() {
        return minimumHours;
    }

    /**
     * Sets the value of the minimumHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMinimumHours(Short value) {
        this.minimumHours = value;
    }

    /**
     * Gets the value of the maximumHours property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMaximumHours() {
        return maximumHours;
    }

    /**
     * Sets the value of the maximumHours property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMaximumHours(Short value) {
        this.maximumHours = value;
    }

    /**
     * Gets the value of the availableDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAvailableDate() {
        return availableDate;
    }

    /**
     * Sets the value of the availableDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvailableDate(XMLGregorianCalendar value) {
        this.availableDate = value;
    }

    /**
     * Gets the value of the availabilityType property.
     * 
     * @return
     *     possible object is
     *     {@link AvailabilityType }
     *     
     */
    public AvailabilityType getAvailabilityType() {
        return availabilityType;
    }

    /**
     * Sets the value of the availabilityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AvailabilityType }
     *     
     */
    public void setAvailabilityType(AvailabilityType value) {
        this.availabilityType = value;
    }

}
