//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GetLowestPricedOffersForASINResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetLowestPricedOffersForASINResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identifier">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MarketplaceId" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MarketplaceType"/>
 *                   &lt;element name="ASIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ItemCondition" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}ConditionType"/>
 *                   &lt;element name="TimeOfOfferChange" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Summary">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TotalOfferCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="NumberOfOffers" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}OfferCountType" minOccurs="0"/>
 *                   &lt;element name="LowestPrices" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="LowestPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}LowestPriceType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="BuyBoxPrices" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BuyBoxPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}BuyBoxPriceType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ListPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType" minOccurs="0"/>
 *                   &lt;element name="SuggestedLowerPricePlusShipping" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType" minOccurs="0"/>
 *                   &lt;element name="BuyBoxEligibleOffers" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}OfferCountType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Offers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Offer" maxOccurs="20" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="SubCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SellerFeedbackRating" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}SellerFeedbackType" minOccurs="0"/>
 *                             &lt;element name="ShippingTime" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}DetailedShippingTimeType"/>
 *                             &lt;element name="ListingPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType"/>
 *                             &lt;element name="Points" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}Points" minOccurs="0"/>
 *                             &lt;element name="Shipping" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType"/>
 *                             &lt;element name="ShipsFrom" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}ShipsFromType" minOccurs="0"/>
 *                             &lt;element name="IsFulfilledByAmazon" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="IsBuyBoxWinner" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                             &lt;element name="IsFeaturedMerchant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="MarketplaceID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ItemCondition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ASIN" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetLowestPricedOffersForASINResult", propOrder = {
    "identifier",
    "summary",
    "offers"
})
public class GetLowestPricedOffersForASINResult {

    @XmlElement(name = "Identifier", required = true)
    protected GetLowestPricedOffersForASINResult.Identifier identifier;
    @XmlElement(name = "Summary", required = true)
    protected GetLowestPricedOffersForASINResult.Summary summary;
    @XmlElement(name = "Offers", required = true)
    protected GetLowestPricedOffersForASINResult.Offers offers;
    @XmlAttribute(name = "MarketplaceID", required = true)
    protected String marketplaceID;
    @XmlAttribute(name = "ItemCondition", required = true)
    protected String itemCondition;
    @XmlAttribute(name = "ASIN", required = true)
    protected String asin;
    @XmlAttribute(name = "status", required = true)
    protected String status;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link GetLowestPricedOffersForASINResult.Identifier }
     *     
     */
    public GetLowestPricedOffersForASINResult.Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetLowestPricedOffersForASINResult.Identifier }
     *     
     */
    public void setIdentifier(GetLowestPricedOffersForASINResult.Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link GetLowestPricedOffersForASINResult.Summary }
     *     
     */
    public GetLowestPricedOffersForASINResult.Summary getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetLowestPricedOffersForASINResult.Summary }
     *     
     */
    public void setSummary(GetLowestPricedOffersForASINResult.Summary value) {
        this.summary = value;
    }

    /**
     * Gets the value of the offers property.
     * 
     * @return
     *     possible object is
     *     {@link GetLowestPricedOffersForASINResult.Offers }
     *     
     */
    public GetLowestPricedOffersForASINResult.Offers getOffers() {
        return offers;
    }

    /**
     * Sets the value of the offers property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetLowestPricedOffersForASINResult.Offers }
     *     
     */
    public void setOffers(GetLowestPricedOffersForASINResult.Offers value) {
        this.offers = value;
    }

    /**
     * Gets the value of the marketplaceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketplaceID() {
        return marketplaceID;
    }

    /**
     * Sets the value of the marketplaceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketplaceID(String value) {
        this.marketplaceID = value;
    }

    /**
     * Gets the value of the itemCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemCondition() {
        return itemCondition;
    }

    /**
     * Sets the value of the itemCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemCondition(String value) {
        this.itemCondition = value;
    }

    /**
     * Gets the value of the asin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASIN() {
        return asin;
    }

    /**
     * Sets the value of the asin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASIN(String value) {
        this.asin = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MarketplaceId" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MarketplaceType"/>
     *         &lt;element name="ASIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ItemCondition" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}ConditionType"/>
     *         &lt;element name="TimeOfOfferChange" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "marketplaceId",
        "asin",
        "itemCondition",
        "timeOfOfferChange"
    })
    public static class Identifier {

        @XmlElement(name = "MarketplaceId", required = true)
        protected String marketplaceId;
        @XmlElement(name = "ASIN", required = true)
        protected String asin;
        @XmlElement(name = "ItemCondition", required = true)
        protected ConditionType itemCondition;
        @XmlElement(name = "TimeOfOfferChange")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timeOfOfferChange;

        /**
         * Gets the value of the marketplaceId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMarketplaceId() {
            return marketplaceId;
        }

        /**
         * Sets the value of the marketplaceId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMarketplaceId(String value) {
            this.marketplaceId = value;
        }

        /**
         * Gets the value of the asin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getASIN() {
            return asin;
        }

        /**
         * Sets the value of the asin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setASIN(String value) {
            this.asin = value;
        }

        /**
         * Gets the value of the itemCondition property.
         * 
         * @return
         *     possible object is
         *     {@link ConditionType }
         *     
         */
        public ConditionType getItemCondition() {
            return itemCondition;
        }

        /**
         * Sets the value of the itemCondition property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConditionType }
         *     
         */
        public void setItemCondition(ConditionType value) {
            this.itemCondition = value;
        }

        /**
         * Gets the value of the timeOfOfferChange property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimeOfOfferChange() {
            return timeOfOfferChange;
        }

        /**
         * Sets the value of the timeOfOfferChange property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimeOfOfferChange(XMLGregorianCalendar value) {
            this.timeOfOfferChange = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Offer" maxOccurs="20" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="SubCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SellerFeedbackRating" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}SellerFeedbackType" minOccurs="0"/>
     *                   &lt;element name="ShippingTime" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}DetailedShippingTimeType"/>
     *                   &lt;element name="ListingPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType"/>
     *                   &lt;element name="Points" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}Points" minOccurs="0"/>
     *                   &lt;element name="Shipping" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType"/>
     *                   &lt;element name="ShipsFrom" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}ShipsFromType" minOccurs="0"/>
     *                   &lt;element name="IsFulfilledByAmazon" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="IsBuyBoxWinner" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                   &lt;element name="IsFeaturedMerchant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "offer"
    })
    public static class Offers {

        @XmlElement(name = "Offer")
        protected List<GetLowestPricedOffersForASINResult.Offers.Offer> offer;

        /**
         * Gets the value of the offer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the offer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOffer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetLowestPricedOffersForASINResult.Offers.Offer }
         * 
         * 
         */
        public List<GetLowestPricedOffersForASINResult.Offers.Offer> getOffer() {
            if (offer == null) {
                offer = new ArrayList<GetLowestPricedOffersForASINResult.Offers.Offer>();
            }
            return this.offer;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="SubCondition" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SellerFeedbackRating" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}SellerFeedbackType" minOccurs="0"/>
         *         &lt;element name="ShippingTime" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}DetailedShippingTimeType"/>
         *         &lt;element name="ListingPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType"/>
         *         &lt;element name="Points" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}Points" minOccurs="0"/>
         *         &lt;element name="Shipping" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType"/>
         *         &lt;element name="ShipsFrom" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}ShipsFromType" minOccurs="0"/>
         *         &lt;element name="IsFulfilledByAmazon" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="IsBuyBoxWinner" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *         &lt;element name="IsFeaturedMerchant" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "subCondition",
            "sellerFeedbackRating",
            "shippingTime",
            "listingPrice",
            "points",
            "shipping",
            "shipsFrom",
            "isFulfilledByAmazon",
            "isBuyBoxWinner",
            "isFeaturedMerchant"
        })
        public static class Offer {

            @XmlElement(name = "SubCondition", required = true)
            protected String subCondition;
            @XmlElement(name = "SellerFeedbackRating")
            protected SellerFeedbackType sellerFeedbackRating;
            @XmlElement(name = "ShippingTime", required = true)
            protected DetailedShippingTimeType shippingTime;
            @XmlElement(name = "ListingPrice", required = true)
            protected MoneyType listingPrice;
            @XmlElement(name = "Points")
            protected Points points;
            @XmlElement(name = "Shipping", required = true)
            protected MoneyType shipping;
            @XmlElement(name = "ShipsFrom")
            protected ShipsFromType shipsFrom;
            @XmlElement(name = "IsFulfilledByAmazon")
            protected boolean isFulfilledByAmazon;
            @XmlElement(name = "IsBuyBoxWinner")
            protected Boolean isBuyBoxWinner;
            @XmlElement(name = "IsFeaturedMerchant")
            protected Boolean isFeaturedMerchant;

            /**
             * Gets the value of the subCondition property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSubCondition() {
                return subCondition;
            }

            /**
             * Sets the value of the subCondition property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubCondition(String value) {
                this.subCondition = value;
            }

            /**
             * Gets the value of the sellerFeedbackRating property.
             * 
             * @return
             *     possible object is
             *     {@link SellerFeedbackType }
             *     
             */
            public SellerFeedbackType getSellerFeedbackRating() {
                return sellerFeedbackRating;
            }

            /**
             * Sets the value of the sellerFeedbackRating property.
             * 
             * @param value
             *     allowed object is
             *     {@link SellerFeedbackType }
             *     
             */
            public void setSellerFeedbackRating(SellerFeedbackType value) {
                this.sellerFeedbackRating = value;
            }

            /**
             * Gets the value of the shippingTime property.
             * 
             * @return
             *     possible object is
             *     {@link DetailedShippingTimeType }
             *     
             */
            public DetailedShippingTimeType getShippingTime() {
                return shippingTime;
            }

            /**
             * Sets the value of the shippingTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link DetailedShippingTimeType }
             *     
             */
            public void setShippingTime(DetailedShippingTimeType value) {
                this.shippingTime = value;
            }

            /**
             * Gets the value of the listingPrice property.
             * 
             * @return
             *     possible object is
             *     {@link MoneyType }
             *     
             */
            public MoneyType getListingPrice() {
                return listingPrice;
            }

            /**
             * Sets the value of the listingPrice property.
             * 
             * @param value
             *     allowed object is
             *     {@link MoneyType }
             *     
             */
            public void setListingPrice(MoneyType value) {
                this.listingPrice = value;
            }

            /**
             * Gets the value of the points property.
             * 
             * @return
             *     possible object is
             *     {@link Points }
             *     
             */
            public Points getPoints() {
                return points;
            }

            /**
             * Sets the value of the points property.
             * 
             * @param value
             *     allowed object is
             *     {@link Points }
             *     
             */
            public void setPoints(Points value) {
                this.points = value;
            }

            /**
             * Gets the value of the shipping property.
             * 
             * @return
             *     possible object is
             *     {@link MoneyType }
             *     
             */
            public MoneyType getShipping() {
                return shipping;
            }

            /**
             * Sets the value of the shipping property.
             * 
             * @param value
             *     allowed object is
             *     {@link MoneyType }
             *     
             */
            public void setShipping(MoneyType value) {
                this.shipping = value;
            }

            /**
             * Gets the value of the shipsFrom property.
             * 
             * @return
             *     possible object is
             *     {@link ShipsFromType }
             *     
             */
            public ShipsFromType getShipsFrom() {
                return shipsFrom;
            }

            /**
             * Sets the value of the shipsFrom property.
             * 
             * @param value
             *     allowed object is
             *     {@link ShipsFromType }
             *     
             */
            public void setShipsFrom(ShipsFromType value) {
                this.shipsFrom = value;
            }

            /**
             * Gets the value of the isFulfilledByAmazon property.
             * 
             */
            public boolean isIsFulfilledByAmazon() {
                return isFulfilledByAmazon;
            }

            /**
             * Sets the value of the isFulfilledByAmazon property.
             * 
             */
            public void setIsFulfilledByAmazon(boolean value) {
                this.isFulfilledByAmazon = value;
            }

            /**
             * Gets the value of the isBuyBoxWinner property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIsBuyBoxWinner() {
                return isBuyBoxWinner;
            }

            /**
             * Sets the value of the isBuyBoxWinner property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIsBuyBoxWinner(Boolean value) {
                this.isBuyBoxWinner = value;
            }

            /**
             * Gets the value of the isFeaturedMerchant property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isIsFeaturedMerchant() {
                return isFeaturedMerchant;
            }

            /**
             * Sets the value of the isFeaturedMerchant property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setIsFeaturedMerchant(Boolean value) {
                this.isFeaturedMerchant = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TotalOfferCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="NumberOfOffers" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}OfferCountType" minOccurs="0"/>
     *         &lt;element name="LowestPrices" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="LowestPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}LowestPriceType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="BuyBoxPrices" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BuyBoxPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}BuyBoxPriceType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ListPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType" minOccurs="0"/>
     *         &lt;element name="SuggestedLowerPricePlusShipping" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MoneyType" minOccurs="0"/>
     *         &lt;element name="BuyBoxEligibleOffers" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}OfferCountType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "totalOfferCount",
        "numberOfOffers",
        "lowestPrices",
        "buyBoxPrices",
        "listPrice",
        "suggestedLowerPricePlusShipping",
        "buyBoxEligibleOffers"
    })
    public static class Summary {

        @XmlElement(name = "TotalOfferCount", required = true)
        protected BigInteger totalOfferCount;
        @XmlElement(name = "NumberOfOffers")
        protected OfferCountType numberOfOffers;
        @XmlElement(name = "LowestPrices")
        protected GetLowestPricedOffersForASINResult.Summary.LowestPrices lowestPrices;
        @XmlElement(name = "BuyBoxPrices")
        protected GetLowestPricedOffersForASINResult.Summary.BuyBoxPrices buyBoxPrices;
        @XmlElement(name = "ListPrice")
        protected MoneyType listPrice;
        @XmlElement(name = "SuggestedLowerPricePlusShipping")
        protected MoneyType suggestedLowerPricePlusShipping;
        @XmlElement(name = "BuyBoxEligibleOffers")
        protected OfferCountType buyBoxEligibleOffers;

        /**
         * Gets the value of the totalOfferCount property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTotalOfferCount() {
            return totalOfferCount;
        }

        /**
         * Sets the value of the totalOfferCount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTotalOfferCount(BigInteger value) {
            this.totalOfferCount = value;
        }

        /**
         * Gets the value of the numberOfOffers property.
         * 
         * @return
         *     possible object is
         *     {@link OfferCountType }
         *     
         */
        public OfferCountType getNumberOfOffers() {
            return numberOfOffers;
        }

        /**
         * Sets the value of the numberOfOffers property.
         * 
         * @param value
         *     allowed object is
         *     {@link OfferCountType }
         *     
         */
        public void setNumberOfOffers(OfferCountType value) {
            this.numberOfOffers = value;
        }

        /**
         * Gets the value of the lowestPrices property.
         * 
         * @return
         *     possible object is
         *     {@link GetLowestPricedOffersForASINResult.Summary.LowestPrices }
         *     
         */
        public GetLowestPricedOffersForASINResult.Summary.LowestPrices getLowestPrices() {
            return lowestPrices;
        }

        /**
         * Sets the value of the lowestPrices property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetLowestPricedOffersForASINResult.Summary.LowestPrices }
         *     
         */
        public void setLowestPrices(GetLowestPricedOffersForASINResult.Summary.LowestPrices value) {
            this.lowestPrices = value;
        }

        /**
         * Gets the value of the buyBoxPrices property.
         * 
         * @return
         *     possible object is
         *     {@link GetLowestPricedOffersForASINResult.Summary.BuyBoxPrices }
         *     
         */
        public GetLowestPricedOffersForASINResult.Summary.BuyBoxPrices getBuyBoxPrices() {
            return buyBoxPrices;
        }

        /**
         * Sets the value of the buyBoxPrices property.
         * 
         * @param value
         *     allowed object is
         *     {@link GetLowestPricedOffersForASINResult.Summary.BuyBoxPrices }
         *     
         */
        public void setBuyBoxPrices(GetLowestPricedOffersForASINResult.Summary.BuyBoxPrices value) {
            this.buyBoxPrices = value;
        }

        /**
         * Gets the value of the listPrice property.
         * 
         * @return
         *     possible object is
         *     {@link MoneyType }
         *     
         */
        public MoneyType getListPrice() {
            return listPrice;
        }

        /**
         * Sets the value of the listPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link MoneyType }
         *     
         */
        public void setListPrice(MoneyType value) {
            this.listPrice = value;
        }

        /**
         * Gets the value of the suggestedLowerPricePlusShipping property.
         * 
         * @return
         *     possible object is
         *     {@link MoneyType }
         *     
         */
        public MoneyType getSuggestedLowerPricePlusShipping() {
            return suggestedLowerPricePlusShipping;
        }

        /**
         * Sets the value of the suggestedLowerPricePlusShipping property.
         * 
         * @param value
         *     allowed object is
         *     {@link MoneyType }
         *     
         */
        public void setSuggestedLowerPricePlusShipping(MoneyType value) {
            this.suggestedLowerPricePlusShipping = value;
        }

        /**
         * Gets the value of the buyBoxEligibleOffers property.
         * 
         * @return
         *     possible object is
         *     {@link OfferCountType }
         *     
         */
        public OfferCountType getBuyBoxEligibleOffers() {
            return buyBoxEligibleOffers;
        }

        /**
         * Sets the value of the buyBoxEligibleOffers property.
         * 
         * @param value
         *     allowed object is
         *     {@link OfferCountType }
         *     
         */
        public void setBuyBoxEligibleOffers(OfferCountType value) {
            this.buyBoxEligibleOffers = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BuyBoxPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}BuyBoxPriceType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "buyBoxPrice"
        })
        public static class BuyBoxPrices {

            @XmlElement(name = "BuyBoxPrice")
            protected List<BuyBoxPriceType> buyBoxPrice;

            /**
             * Gets the value of the buyBoxPrice property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the buyBoxPrice property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBuyBoxPrice().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BuyBoxPriceType }
             * 
             * 
             */
            public List<BuyBoxPriceType> getBuyBoxPrice() {
                if (buyBoxPrice == null) {
                    buyBoxPrice = new ArrayList<BuyBoxPriceType>();
                }
                return this.buyBoxPrice;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="LowestPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}LowestPriceType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lowestPrice"
        })
        public static class LowestPrices {

            @XmlElement(name = "LowestPrice")
            protected List<LowestPriceType> lowestPrice;

            /**
             * Gets the value of the lowestPrice property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the lowestPrice property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getLowestPrice().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link LowestPriceType }
             * 
             * 
             */
            public List<LowestPriceType> getLowestPrice() {
                if (lowestPrice == null) {
                    lowestPrice = new ArrayList<LowestPriceType>();
                }
                return this.lowestPrice;
            }

        }

    }

}
