//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdentifierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentifierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MarketplaceASIN" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}MarketplaceASINType"/>
 *         &lt;element name="SKUIdentifier" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}SellerSKUIdentifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentifierType", propOrder = {
    "marketplaceASIN",
    "skuIdentifier"
})
public class IdentifierType {

    @XmlElement(name = "MarketplaceASIN", required = true)
    protected MarketplaceASINType marketplaceASIN;
    @XmlElement(name = "SKUIdentifier")
    protected SellerSKUIdentifier skuIdentifier;

    /**
     * Gets the value of the marketplaceASIN property.
     * 
     * @return
     *     possible object is
     *     {@link MarketplaceASINType }
     *     
     */
    public MarketplaceASINType getMarketplaceASIN() {
        return marketplaceASIN;
    }

    /**
     * Sets the value of the marketplaceASIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketplaceASINType }
     *     
     */
    public void setMarketplaceASIN(MarketplaceASINType value) {
        this.marketplaceASIN = value;
    }

    /**
     * Gets the value of the skuIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link SellerSKUIdentifier }
     *     
     */
    public SellerSKUIdentifier getSKUIdentifier() {
        return skuIdentifier;
    }

    /**
     * Sets the value of the skuIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SellerSKUIdentifier }
     *     
     */
    public void setSKUIdentifier(SellerSKUIdentifier value) {
        this.skuIdentifier = value;
    }

}
