//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//

package com.amazonaws.mws.model.response;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ItemAttributesType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ItemAttributesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://mws.amazonservices.com/schema/Products/2011-10-01}AttributeSetType">
 *       &lt;sequence>
 *         &lt;element name="Actor" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Artist" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AspectRatio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AudienceRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="BackFinding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BandMaterialType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Binding" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BlurayRegion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Brand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CEROAgeRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChainType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClaspType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CPUManufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CPUSpeed" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="CPUType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Creator" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}CreatorType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Department" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Director" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DisplaySize" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="Edition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EpisodeSequence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ESRBAgeRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Feature" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Flavor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GemType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Genre" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GolfClubFlex" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GolfClubLoft" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="HandOrientation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HardDiskInterface" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HardDiskSize" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="HardwarePlatform" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HazardousMaterialType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ItemDimensions" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DimensionType" minOccurs="0"/>
 *         &lt;element name="IsAdultProduct" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsAutographed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsEligibleForTradeIn" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IsMemorabilia" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="IssuesPerYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ItemPartNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Languages" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}LanguageType" minOccurs="0"/>
 *         &lt;element name="LegalDisclaimer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ListPrice" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}Price" minOccurs="0"/>
 *         &lt;element name="Manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ManufacturerMaximumAge" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="ManufacturerMinimumAge" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="ManufacturerPartsWarrantyDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaterialType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MaximumResolution" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="MediaType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MetalStamp" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MetalType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumberOfDiscs" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="NumberOfIssues" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="NumberOfItems" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="NumberOfPages" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="NumberOfTracks" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="OperatingSystem" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OpticalZoom" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="PackageDimensions" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DimensionType" minOccurs="0"/>
 *         &lt;element name="PackageQuantity" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="PartNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PegiRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Platform" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProcessorCount" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="ProductGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductTypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProductTypeSubcategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PublicationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Publisher" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleaseDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RingSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RunningTime" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="ShaftMaterial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Scent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SeasonSequence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SeikodoProductCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Size" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SizePerPearl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SmallImage" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}Image" minOccurs="0"/>
 *         &lt;element name="Studio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubscriptionLength" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}NonNegativeIntegerWithUnits" minOccurs="0"/>
 *         &lt;element name="SystemMemorySize" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="SystemMemoryType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TheatricalReleaseDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalDiamondWeight" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="TotalGemWeight" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}DecimalWithUnits" minOccurs="0"/>
 *         &lt;element name="Warranty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WEEETaxValue" type="{http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd}Price" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemAttributesType", namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd", propOrder = {
		"actor", "artist", "aspectRatio", "audienceRating", "author", "backFinding", "bandMaterialType", "binding",
		"blurayRegion", "brand", "ceroAgeRating", "chainType", "claspType", "color", "cpuManufacturer", "cpuSpeed",
		"cpuType", "creator", "department", "director", "displaySize", "edition", "episodeSequence", "esrbAgeRating",
		"feature", "flavor", "format", "gemType", "genre", "golfClubFlex", "golfClubLoft", "handOrientation",
		"hardDiskInterface", "hardDiskSize", "hardwarePlatform", "hazardousMaterialType", "itemDimensions",
		"isAdultProduct", "isAutographed", "isEligibleForTradeIn", "isMemorabilia", "issuesPerYear", "itemPartNumber",
		"label", "languages", "legalDisclaimer", "listPrice", "manufacturer", "manufacturerMaximumAge",
		"manufacturerMinimumAge", "manufacturerPartsWarrantyDescription", "materialType", "maximumResolution",
		"mediaType", "metalStamp", "metalType", "model", "numberOfDiscs", "numberOfIssues", "numberOfItems",
		"numberOfPages", "numberOfTracks", "operatingSystem", "opticalZoom", "packageDimensions", "packageQuantity",
		"partNumber", "pegiRating", "platform", "processorCount", "productGroup", "productTypeName",
		"productTypeSubcategory", "publicationDate", "publisher", "regionCode", "releaseDate", "ringSize",
		"runningTime", "shaftMaterial", "scent", "seasonSequence", "seikodoProductCode", "size", "sizePerPearl",
		"smallImage", "studio", "subscriptionLength", "systemMemorySize", "systemMemoryType", "theatricalReleaseDate",
		"title", "totalDiamondWeight", "totalGemWeight", "warranty", "weeeTaxValue" })
@XmlRootElement(name = "ItemAttributes", namespace = "ns2")
public class ItemAttributesType extends AttributeSetType {

	@XmlElement(name = "Actor")
	protected List<String> actor;
	@XmlElement(name = "Artist")
	protected List<String> artist;
	@XmlElement(name = "AspectRatio")
	protected String aspectRatio;
	@XmlElement(name = "AudienceRating")
	protected String audienceRating;
	@XmlElement(name = "Author")
	protected List<String> author;
	@XmlElement(name = "BackFinding")
	protected String backFinding;
	@XmlElement(name = "BandMaterialType")
	protected String bandMaterialType;
	@XmlElement(name = "Binding")
	protected String binding;
	@XmlElement(name = "BlurayRegion")
	protected String blurayRegion;
	@XmlElement(name = "Brand")
	protected String brand;
	@XmlElement(name = "CEROAgeRating")
	protected String ceroAgeRating;
	@XmlElement(name = "ChainType")
	protected String chainType;
	@XmlElement(name = "ClaspType")
	protected String claspType;
	@XmlElement(name = "Color")
	protected String color;
	@XmlElement(name = "CPUManufacturer")
	protected String cpuManufacturer;
	@XmlElement(name = "CPUSpeed")
	protected DecimalWithUnits cpuSpeed;
	@XmlElement(name = "CPUType")
	protected String cpuType;
	@XmlElement(name = "Creator")
	protected List<CreatorType> creator;
	@XmlElement(name = "Department")
	protected String department;
	@XmlElement(name = "Director")
	protected List<String> director;
	@XmlElement(name = "DisplaySize")
	protected DecimalWithUnits displaySize;
	@XmlElement(name = "Edition")
	protected String edition;
	@XmlElement(name = "EpisodeSequence")
	protected String episodeSequence;
	@XmlElement(name = "ESRBAgeRating")
	protected String esrbAgeRating;
	@XmlElement(name = "Feature")
	protected List<String> feature;
	@XmlElement(name = "Flavor")
	protected String flavor;
	@XmlElement(name = "Format")
	protected List<String> format;
	@XmlElement(name = "GemType")
	protected List<String> gemType;
	@XmlElement(name = "Genre")
	protected String genre;
	@XmlElement(name = "GolfClubFlex")
	protected String golfClubFlex;
	@XmlElement(name = "GolfClubLoft")
	protected DecimalWithUnits golfClubLoft;
	@XmlElement(name = "HandOrientation")
	protected String handOrientation;
	@XmlElement(name = "HardDiskInterface")
	protected String hardDiskInterface;
	@XmlElement(name = "HardDiskSize")
	protected DecimalWithUnits hardDiskSize;
	@XmlElement(name = "HardwarePlatform")
	protected String hardwarePlatform;
	@XmlElement(name = "HazardousMaterialType")
	protected String hazardousMaterialType;
	@XmlElement(name = "ItemDimensions")
	protected DimensionType itemDimensions;
	@XmlElement(name = "IsAdultProduct")
	protected Boolean isAdultProduct;
	@XmlElement(name = "IsAutographed")
	protected Boolean isAutographed;
	@XmlElement(name = "IsEligibleForTradeIn")
	protected Boolean isEligibleForTradeIn;
	@XmlElement(name = "IsMemorabilia")
	protected Boolean isMemorabilia;
	@XmlElement(name = "IssuesPerYear")
	protected String issuesPerYear;
	@XmlElement(name = "ItemPartNumber")
	protected String itemPartNumber;
	@XmlElement(name = "Label")
	protected String label;
	@XmlElement(name = "Languages")
	protected LanguageType languages;
	@XmlElement(name = "LegalDisclaimer")
	protected String legalDisclaimer;
	@XmlElement(name = "ListPrice")
	protected Price listPrice;
	@XmlElement(name = "Manufacturer")
	protected String manufacturer;
	@XmlElement(name = "ManufacturerMaximumAge")
	protected DecimalWithUnits manufacturerMaximumAge;
	@XmlElement(name = "ManufacturerMinimumAge")
	protected DecimalWithUnits manufacturerMinimumAge;
	@XmlElement(name = "ManufacturerPartsWarrantyDescription")
	protected String manufacturerPartsWarrantyDescription;
	@XmlElement(name = "MaterialType")
	protected List<String> materialType;
	@XmlElement(name = "MaximumResolution")
	protected DecimalWithUnits maximumResolution;
	@XmlElement(name = "MediaType")
	protected List<String> mediaType;
	@XmlElement(name = "MetalStamp")
	protected String metalStamp;
	@XmlElement(name = "MetalType")
	protected String metalType;
	@XmlElement(name = "Model")
	protected String model;
	@XmlElement(name = "NumberOfDiscs")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger numberOfDiscs;
	@XmlElement(name = "NumberOfIssues")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger numberOfIssues;
	@XmlElement(name = "NumberOfItems")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger numberOfItems;
	@XmlElement(name = "NumberOfPages")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger numberOfPages;
	@XmlElement(name = "NumberOfTracks")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger numberOfTracks;
	@XmlElement(name = "OperatingSystem")
	protected List<String> operatingSystem;
	@XmlElement(name = "OpticalZoom")
	protected DecimalWithUnits opticalZoom;
	@XmlElement(name = "PackageDimensions")
	protected DimensionType packageDimensions;
	@XmlElement(name = "PackageQuantity")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger packageQuantity;
	@XmlElement(name = "PartNumber")
	protected String partNumber;
	@XmlElement(name = "PegiRating")
	protected String pegiRating;
	@XmlElement(name = "Platform")
	protected List<String> platform;
	@XmlElement(name = "ProcessorCount")
	@XmlSchemaType(name = "nonNegativeInteger")
	protected BigInteger processorCount;
	@XmlElement(name = "ProductGroup")
	protected String productGroup;
	@XmlElement(name = "ProductTypeName")
	protected String productTypeName;
	@XmlElement(name = "ProductTypeSubcategory")
	protected String productTypeSubcategory;
	@XmlElement(name = "PublicationDate")
	protected String publicationDate;
	@XmlElement(name = "Publisher")
	protected String publisher;
	@XmlElement(name = "RegionCode")
	protected String regionCode;
	@XmlElement(name = "ReleaseDate")
	protected String releaseDate;
	@XmlElement(name = "RingSize")
	protected String ringSize;
	@XmlElement(name = "RunningTime")
	protected DecimalWithUnits runningTime;
	@XmlElement(name = "ShaftMaterial")
	protected String shaftMaterial;
	@XmlElement(name = "Scent")
	protected String scent;
	@XmlElement(name = "SeasonSequence")
	protected String seasonSequence;
	@XmlElement(name = "SeikodoProductCode")
	protected String seikodoProductCode;
	@XmlElement(name = "Size")
	protected String size;
	@XmlElement(name = "SizePerPearl")
	protected String sizePerPearl;
	@XmlElement(name = "SmallImage")
	protected Image smallImage;
	@XmlElement(name = "Studio")
	protected String studio;
	@XmlElement(name = "SubscriptionLength")
	protected NonNegativeIntegerWithUnits subscriptionLength;
	@XmlElement(name = "SystemMemorySize")
	protected DecimalWithUnits systemMemorySize;
	@XmlElement(name = "SystemMemoryType")
	protected String systemMemoryType;
	@XmlElement(name = "TheatricalReleaseDate")
	protected String theatricalReleaseDate;
	@XmlElement(name = "Title")
	protected String title;
	@XmlElement(name = "TotalDiamondWeight")
	protected DecimalWithUnits totalDiamondWeight;
	@XmlElement(name = "TotalGemWeight")
	protected DecimalWithUnits totalGemWeight;
	@XmlElement(name = "Warranty")
	protected String warranty;
	@XmlElement(name = "WEEETaxValue")
	protected Price weeeTaxValue;

	/**
	 * Gets the value of the actor property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the actor property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getActor().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getActor() {
		if (actor == null) {
			actor = new ArrayList<String>();
		}
		return this.actor;
	}

	/**
	 * Gets the value of the artist property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the artist property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getArtist().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getArtist() {
		if (artist == null) {
			artist = new ArrayList<String>();
		}
		return this.artist;
	}

	/**
	 * Gets the value of the aspectRatio property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAspectRatio() {
		return aspectRatio;
	}

	/**
	 * Sets the value of the aspectRatio property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAspectRatio(String value) {
		this.aspectRatio = value;
	}

	/**
	 * Gets the value of the audienceRating property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAudienceRating() {
		return audienceRating;
	}

	/**
	 * Sets the value of the audienceRating property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAudienceRating(String value) {
		this.audienceRating = value;
	}

	/**
	 * Gets the value of the author property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the author property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAuthor().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getAuthor() {
		if (author == null) {
			author = new ArrayList<String>();
		}
		return this.author;
	}

	/**
	 * Gets the value of the backFinding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBackFinding() {
		return backFinding;
	}

	/**
	 * Sets the value of the backFinding property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBackFinding(String value) {
		this.backFinding = value;
	}

	/**
	 * Gets the value of the bandMaterialType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBandMaterialType() {
		return bandMaterialType;
	}

	/**
	 * Sets the value of the bandMaterialType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBandMaterialType(String value) {
		this.bandMaterialType = value;
	}

	/**
	 * Gets the value of the binding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBinding() {
		return binding;
	}

	/**
	 * Sets the value of the binding property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBinding(String value) {
		this.binding = value;
	}

	/**
	 * Gets the value of the blurayRegion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBlurayRegion() {
		return blurayRegion;
	}

	/**
	 * Sets the value of the blurayRegion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBlurayRegion(String value) {
		this.blurayRegion = value;
	}

	/**
	 * Gets the value of the brand property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBrand() {
		return brand;
	}

	/**
	 * Sets the value of the brand property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBrand(String value) {
		this.brand = value;
	}

	/**
	 * Gets the value of the ceroAgeRating property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCEROAgeRating() {
		return ceroAgeRating;
	}

	/**
	 * Sets the value of the ceroAgeRating property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCEROAgeRating(String value) {
		this.ceroAgeRating = value;
	}

	/**
	 * Gets the value of the chainType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChainType() {
		return chainType;
	}

	/**
	 * Sets the value of the chainType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChainType(String value) {
		this.chainType = value;
	}

	/**
	 * Gets the value of the claspType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClaspType() {
		return claspType;
	}

	/**
	 * Sets the value of the claspType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setClaspType(String value) {
		this.claspType = value;
	}

	/**
	 * Gets the value of the color property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getColor() {
		return color;
	}

	/**
	 * Sets the value of the color property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setColor(String value) {
		this.color = value;
	}

	/**
	 * Gets the value of the cpuManufacturer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCPUManufacturer() {
		return cpuManufacturer;
	}

	/**
	 * Sets the value of the cpuManufacturer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCPUManufacturer(String value) {
		this.cpuManufacturer = value;
	}

	/**
	 * Gets the value of the cpuSpeed property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getCPUSpeed() {
		return cpuSpeed;
	}

	/**
	 * Sets the value of the cpuSpeed property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setCPUSpeed(DecimalWithUnits value) {
		this.cpuSpeed = value;
	}

	/**
	 * Gets the value of the cpuType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCPUType() {
		return cpuType;
	}

	/**
	 * Sets the value of the cpuType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCPUType(String value) {
		this.cpuType = value;
	}

	/**
	 * Gets the value of the creator property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the creator property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getCreator().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link CreatorType }
	 * 
	 * 
	 */
	public List<CreatorType> getCreator() {
		if (creator == null) {
			creator = new ArrayList<CreatorType>();
		}
		return this.creator;
	}

	/**
	 * Gets the value of the department property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * Sets the value of the department property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDepartment(String value) {
		this.department = value;
	}

	/**
	 * Gets the value of the director property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the director property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDirector().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getDirector() {
		if (director == null) {
			director = new ArrayList<String>();
		}
		return this.director;
	}

	/**
	 * Gets the value of the displaySize property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getDisplaySize() {
		return displaySize;
	}

	/**
	 * Sets the value of the displaySize property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setDisplaySize(DecimalWithUnits value) {
		this.displaySize = value;
	}

	/**
	 * Gets the value of the edition property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEdition() {
		return edition;
	}

	/**
	 * Sets the value of the edition property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEdition(String value) {
		this.edition = value;
	}

	/**
	 * Gets the value of the episodeSequence property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEpisodeSequence() {
		return episodeSequence;
	}

	/**
	 * Sets the value of the episodeSequence property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEpisodeSequence(String value) {
		this.episodeSequence = value;
	}

	/**
	 * Gets the value of the esrbAgeRating property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getESRBAgeRating() {
		return esrbAgeRating;
	}

	/**
	 * Sets the value of the esrbAgeRating property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setESRBAgeRating(String value) {
		this.esrbAgeRating = value;
	}

	/**
	 * Gets the value of the feature property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the feature property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFeature().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getFeature() {
		if (feature == null) {
			feature = new ArrayList<String>();
		}
		return this.feature;
	}

	/**
	 * Gets the value of the flavor property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFlavor() {
		return flavor;
	}

	/**
	 * Sets the value of the flavor property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFlavor(String value) {
		this.flavor = value;
	}

	/**
	 * Gets the value of the format property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the format property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFormat().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getFormat() {
		if (format == null) {
			format = new ArrayList<String>();
		}
		return this.format;
	}

	/**
	 * Gets the value of the gemType property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the gemType property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getGemType().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getGemType() {
		if (gemType == null) {
			gemType = new ArrayList<String>();
		}
		return this.gemType;
	}

	/**
	 * Gets the value of the genre property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGenre() {
		return genre;
	}

	/**
	 * Sets the value of the genre property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGenre(String value) {
		this.genre = value;
	}

	/**
	 * Gets the value of the golfClubFlex property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGolfClubFlex() {
		return golfClubFlex;
	}

	/**
	 * Sets the value of the golfClubFlex property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGolfClubFlex(String value) {
		this.golfClubFlex = value;
	}

	/**
	 * Gets the value of the golfClubLoft property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getGolfClubLoft() {
		return golfClubLoft;
	}

	/**
	 * Sets the value of the golfClubLoft property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setGolfClubLoft(DecimalWithUnits value) {
		this.golfClubLoft = value;
	}

	/**
	 * Gets the value of the handOrientation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHandOrientation() {
		return handOrientation;
	}

	/**
	 * Sets the value of the handOrientation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHandOrientation(String value) {
		this.handOrientation = value;
	}

	/**
	 * Gets the value of the hardDiskInterface property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHardDiskInterface() {
		return hardDiskInterface;
	}

	/**
	 * Sets the value of the hardDiskInterface property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHardDiskInterface(String value) {
		this.hardDiskInterface = value;
	}

	/**
	 * Gets the value of the hardDiskSize property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getHardDiskSize() {
		return hardDiskSize;
	}

	/**
	 * Sets the value of the hardDiskSize property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setHardDiskSize(DecimalWithUnits value) {
		this.hardDiskSize = value;
	}

	/**
	 * Gets the value of the hardwarePlatform property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHardwarePlatform() {
		return hardwarePlatform;
	}

	/**
	 * Sets the value of the hardwarePlatform property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHardwarePlatform(String value) {
		this.hardwarePlatform = value;
	}

	/**
	 * Gets the value of the hazardousMaterialType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getHazardousMaterialType() {
		return hazardousMaterialType;
	}

	/**
	 * Sets the value of the hazardousMaterialType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setHazardousMaterialType(String value) {
		this.hazardousMaterialType = value;
	}

	/**
	 * Gets the value of the itemDimensions property.
	 * 
	 * @return possible object is {@link DimensionType }
	 * 
	 */
	public DimensionType getItemDimensions() {
		return itemDimensions;
	}

	/**
	 * Sets the value of the itemDimensions property.
	 * 
	 * @param value
	 *            allowed object is {@link DimensionType }
	 * 
	 */
	public void setItemDimensions(DimensionType value) {
		this.itemDimensions = value;
	}

	/**
	 * Gets the value of the isAdultProduct property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isIsAdultProduct() {
		return isAdultProduct;
	}

	/**
	 * Sets the value of the isAdultProduct property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIsAdultProduct(Boolean value) {
		this.isAdultProduct = value;
	}

	/**
	 * Gets the value of the isAutographed property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isIsAutographed() {
		return isAutographed;
	}

	/**
	 * Sets the value of the isAutographed property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIsAutographed(Boolean value) {
		this.isAutographed = value;
	}

	/**
	 * Gets the value of the isEligibleForTradeIn property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isIsEligibleForTradeIn() {
		return isEligibleForTradeIn;
	}

	/**
	 * Sets the value of the isEligibleForTradeIn property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIsEligibleForTradeIn(Boolean value) {
		this.isEligibleForTradeIn = value;
	}

	/**
	 * Gets the value of the isMemorabilia property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isIsMemorabilia() {
		return isMemorabilia;
	}

	/**
	 * Sets the value of the isMemorabilia property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setIsMemorabilia(Boolean value) {
		this.isMemorabilia = value;
	}

	/**
	 * Gets the value of the issuesPerYear property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIssuesPerYear() {
		return issuesPerYear;
	}

	/**
	 * Sets the value of the issuesPerYear property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIssuesPerYear(String value) {
		this.issuesPerYear = value;
	}

	/**
	 * Gets the value of the itemPartNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getItemPartNumber() {
		return itemPartNumber;
	}

	/**
	 * Sets the value of the itemPartNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setItemPartNumber(String value) {
		this.itemPartNumber = value;
	}

	/**
	 * Gets the value of the label property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLabel() {
		return label;
	}

	/**
	 * Sets the value of the label property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLabel(String value) {
		this.label = value;
	}

	/**
	 * Gets the value of the languages property.
	 * 
	 * @return possible object is {@link LanguageType }
	 * 
	 */
	public LanguageType getLanguages() {
		return languages;
	}

	/**
	 * Sets the value of the languages property.
	 * 
	 * @param value
	 *            allowed object is {@link LanguageType }
	 * 
	 */
	public void setLanguages(LanguageType value) {
		this.languages = value;
	}

	/**
	 * Gets the value of the legalDisclaimer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLegalDisclaimer() {
		return legalDisclaimer;
	}

	/**
	 * Sets the value of the legalDisclaimer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLegalDisclaimer(String value) {
		this.legalDisclaimer = value;
	}

	/**
	 * Gets the value of the listPrice property.
	 * 
	 * @return possible object is {@link Price }
	 * 
	 */
	public Price getListPrice() {
		return listPrice;
	}

	/**
	 * Sets the value of the listPrice property.
	 * 
	 * @param value
	 *            allowed object is {@link Price }
	 * 
	 */
	public void setListPrice(Price value) {
		this.listPrice = value;
	}

	/**
	 * Gets the value of the manufacturer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/**
	 * Sets the value of the manufacturer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManufacturer(String value) {
		this.manufacturer = value;
	}

	/**
	 * Gets the value of the manufacturerMaximumAge property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getManufacturerMaximumAge() {
		return manufacturerMaximumAge;
	}

	/**
	 * Sets the value of the manufacturerMaximumAge property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setManufacturerMaximumAge(DecimalWithUnits value) {
		this.manufacturerMaximumAge = value;
	}

	/**
	 * Gets the value of the manufacturerMinimumAge property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getManufacturerMinimumAge() {
		return manufacturerMinimumAge;
	}

	/**
	 * Sets the value of the manufacturerMinimumAge property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setManufacturerMinimumAge(DecimalWithUnits value) {
		this.manufacturerMinimumAge = value;
	}

	/**
	 * Gets the value of the manufacturerPartsWarrantyDescription property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManufacturerPartsWarrantyDescription() {
		return manufacturerPartsWarrantyDescription;
	}

	/**
	 * Sets the value of the manufacturerPartsWarrantyDescription property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManufacturerPartsWarrantyDescription(String value) {
		this.manufacturerPartsWarrantyDescription = value;
	}

	/**
	 * Gets the value of the materialType property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the materialType property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMaterialType().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getMaterialType() {
		if (materialType == null) {
			materialType = new ArrayList<String>();
		}
		return this.materialType;
	}

	/**
	 * Gets the value of the maximumResolution property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getMaximumResolution() {
		return maximumResolution;
	}

	/**
	 * Sets the value of the maximumResolution property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setMaximumResolution(DecimalWithUnits value) {
		this.maximumResolution = value;
	}

	/**
	 * Gets the value of the mediaType property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the mediaType property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMediaType().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getMediaType() {
		if (mediaType == null) {
			mediaType = new ArrayList<String>();
		}
		return this.mediaType;
	}

	/**
	 * Gets the value of the metalStamp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMetalStamp() {
		return metalStamp;
	}

	/**
	 * Sets the value of the metalStamp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMetalStamp(String value) {
		this.metalStamp = value;
	}

	/**
	 * Gets the value of the metalType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMetalType() {
		return metalType;
	}

	/**
	 * Sets the value of the metalType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMetalType(String value) {
		this.metalType = value;
	}

	/**
	 * Gets the value of the model property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getModel() {
		return model;
	}

	/**
	 * Sets the value of the model property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setModel(String value) {
		this.model = value;
	}

	/**
	 * Gets the value of the numberOfDiscs property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNumberOfDiscs() {
		return numberOfDiscs;
	}

	/**
	 * Sets the value of the numberOfDiscs property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNumberOfDiscs(BigInteger value) {
		this.numberOfDiscs = value;
	}

	/**
	 * Gets the value of the numberOfIssues property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNumberOfIssues() {
		return numberOfIssues;
	}

	/**
	 * Sets the value of the numberOfIssues property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNumberOfIssues(BigInteger value) {
		this.numberOfIssues = value;
	}

	/**
	 * Gets the value of the numberOfItems property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNumberOfItems() {
		return numberOfItems;
	}

	/**
	 * Sets the value of the numberOfItems property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNumberOfItems(BigInteger value) {
		this.numberOfItems = value;
	}

	/**
	 * Gets the value of the numberOfPages property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNumberOfPages() {
		return numberOfPages;
	}

	/**
	 * Sets the value of the numberOfPages property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNumberOfPages(BigInteger value) {
		this.numberOfPages = value;
	}

	/**
	 * Gets the value of the numberOfTracks property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNumberOfTracks() {
		return numberOfTracks;
	}

	/**
	 * Sets the value of the numberOfTracks property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setNumberOfTracks(BigInteger value) {
		this.numberOfTracks = value;
	}

	/**
	 * Gets the value of the operatingSystem property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the operatingSystem property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getOperatingSystem().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getOperatingSystem() {
		if (operatingSystem == null) {
			operatingSystem = new ArrayList<String>();
		}
		return this.operatingSystem;
	}

	/**
	 * Gets the value of the opticalZoom property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getOpticalZoom() {
		return opticalZoom;
	}

	/**
	 * Sets the value of the opticalZoom property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setOpticalZoom(DecimalWithUnits value) {
		this.opticalZoom = value;
	}

	/**
	 * Gets the value of the packageDimensions property.
	 * 
	 * @return possible object is {@link DimensionType }
	 * 
	 */
	public DimensionType getPackageDimensions() {
		return packageDimensions;
	}

	/**
	 * Sets the value of the packageDimensions property.
	 * 
	 * @param value
	 *            allowed object is {@link DimensionType }
	 * 
	 */
	public void setPackageDimensions(DimensionType value) {
		this.packageDimensions = value;
	}

	/**
	 * Gets the value of the packageQuantity property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getPackageQuantity() {
		return packageQuantity;
	}

	/**
	 * Sets the value of the packageQuantity property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setPackageQuantity(BigInteger value) {
		this.packageQuantity = value;
	}

	/**
	 * Gets the value of the partNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPartNumber() {
		return partNumber;
	}

	/**
	 * Sets the value of the partNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPartNumber(String value) {
		this.partNumber = value;
	}

	/**
	 * Gets the value of the pegiRating property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPegiRating() {
		return pegiRating;
	}

	/**
	 * Sets the value of the pegiRating property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPegiRating(String value) {
		this.pegiRating = value;
	}

	/**
	 * Gets the value of the platform property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the platform property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPlatform().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getPlatform() {
		if (platform == null) {
			platform = new ArrayList<String>();
		}
		return this.platform;
	}

	/**
	 * Gets the value of the processorCount property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getProcessorCount() {
		return processorCount;
	}

	/**
	 * Sets the value of the processorCount property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setProcessorCount(BigInteger value) {
		this.processorCount = value;
	}

	/**
	 * Gets the value of the productGroup property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductGroup() {
		return productGroup;
	}

	/**
	 * Sets the value of the productGroup property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProductGroup(String value) {
		this.productGroup = value;
	}

	/**
	 * Gets the value of the productTypeName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductTypeName() {
		return productTypeName;
	}

	/**
	 * Sets the value of the productTypeName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProductTypeName(String value) {
		this.productTypeName = value;
	}

	/**
	 * Gets the value of the productTypeSubcategory property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductTypeSubcategory() {
		return productTypeSubcategory;
	}

	/**
	 * Sets the value of the productTypeSubcategory property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProductTypeSubcategory(String value) {
		this.productTypeSubcategory = value;
	}

	/**
	 * Gets the value of the publicationDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPublicationDate() {
		return publicationDate;
	}

	/**
	 * Sets the value of the publicationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPublicationDate(String value) {
		this.publicationDate = value;
	}

	/**
	 * Gets the value of the publisher property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPublisher() {
		return publisher;
	}

	/**
	 * Sets the value of the publisher property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPublisher(String value) {
		this.publisher = value;
	}

	/**
	 * Gets the value of the regionCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRegionCode() {
		return regionCode;
	}

	/**
	 * Sets the value of the regionCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRegionCode(String value) {
		this.regionCode = value;
	}

	/**
	 * Gets the value of the releaseDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReleaseDate() {
		return releaseDate;
	}

	/**
	 * Sets the value of the releaseDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReleaseDate(String value) {
		this.releaseDate = value;
	}

	/**
	 * Gets the value of the ringSize property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRingSize() {
		return ringSize;
	}

	/**
	 * Sets the value of the ringSize property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRingSize(String value) {
		this.ringSize = value;
	}

	/**
	 * Gets the value of the runningTime property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getRunningTime() {
		return runningTime;
	}

	/**
	 * Sets the value of the runningTime property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setRunningTime(DecimalWithUnits value) {
		this.runningTime = value;
	}

	/**
	 * Gets the value of the shaftMaterial property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getShaftMaterial() {
		return shaftMaterial;
	}

	/**
	 * Sets the value of the shaftMaterial property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setShaftMaterial(String value) {
		this.shaftMaterial = value;
	}

	/**
	 * Gets the value of the scent property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScent() {
		return scent;
	}

	/**
	 * Sets the value of the scent property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScent(String value) {
		this.scent = value;
	}

	/**
	 * Gets the value of the seasonSequence property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSeasonSequence() {
		return seasonSequence;
	}

	/**
	 * Sets the value of the seasonSequence property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSeasonSequence(String value) {
		this.seasonSequence = value;
	}

	/**
	 * Gets the value of the seikodoProductCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSeikodoProductCode() {
		return seikodoProductCode;
	}

	/**
	 * Sets the value of the seikodoProductCode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSeikodoProductCode(String value) {
		this.seikodoProductCode = value;
	}

	/**
	 * Gets the value of the size property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSize() {
		return size;
	}

	/**
	 * Sets the value of the size property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSize(String value) {
		this.size = value;
	}

	/**
	 * Gets the value of the sizePerPearl property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSizePerPearl() {
		return sizePerPearl;
	}

	/**
	 * Sets the value of the sizePerPearl property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSizePerPearl(String value) {
		this.sizePerPearl = value;
	}

	/**
	 * Gets the value of the smallImage property.
	 * 
	 * @return possible object is {@link Image }
	 * 
	 */
	public Image getSmallImage() {
		return smallImage;
	}

	/**
	 * Sets the value of the smallImage property.
	 * 
	 * @param value
	 *            allowed object is {@link Image }
	 * 
	 */
	public void setSmallImage(Image value) {
		this.smallImage = value;
	}

	/**
	 * Gets the value of the studio property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStudio() {
		return studio;
	}

	/**
	 * Sets the value of the studio property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStudio(String value) {
		this.studio = value;
	}

	/**
	 * Gets the value of the subscriptionLength property.
	 * 
	 * @return possible object is {@link NonNegativeIntegerWithUnits }
	 * 
	 */
	public NonNegativeIntegerWithUnits getSubscriptionLength() {
		return subscriptionLength;
	}

	/**
	 * Sets the value of the subscriptionLength property.
	 * 
	 * @param value
	 *            allowed object is {@link NonNegativeIntegerWithUnits }
	 * 
	 */
	public void setSubscriptionLength(NonNegativeIntegerWithUnits value) {
		this.subscriptionLength = value;
	}

	/**
	 * Gets the value of the systemMemorySize property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getSystemMemorySize() {
		return systemMemorySize;
	}

	/**
	 * Sets the value of the systemMemorySize property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setSystemMemorySize(DecimalWithUnits value) {
		this.systemMemorySize = value;
	}

	/**
	 * Gets the value of the systemMemoryType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSystemMemoryType() {
		return systemMemoryType;
	}

	/**
	 * Sets the value of the systemMemoryType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSystemMemoryType(String value) {
		this.systemMemoryType = value;
	}

	/**
	 * Gets the value of the theatricalReleaseDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTheatricalReleaseDate() {
		return theatricalReleaseDate;
	}

	/**
	 * Sets the value of the theatricalReleaseDate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTheatricalReleaseDate(String value) {
		this.theatricalReleaseDate = value;
	}

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the totalDiamondWeight property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getTotalDiamondWeight() {
		return totalDiamondWeight;
	}

	/**
	 * Sets the value of the totalDiamondWeight property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setTotalDiamondWeight(DecimalWithUnits value) {
		this.totalDiamondWeight = value;
	}

	/**
	 * Gets the value of the totalGemWeight property.
	 * 
	 * @return possible object is {@link DecimalWithUnits }
	 * 
	 */
	public DecimalWithUnits getTotalGemWeight() {
		return totalGemWeight;
	}

	/**
	 * Sets the value of the totalGemWeight property.
	 * 
	 * @param value
	 *            allowed object is {@link DecimalWithUnits }
	 * 
	 */
	public void setTotalGemWeight(DecimalWithUnits value) {
		this.totalGemWeight = value;
	}

	/**
	 * Gets the value of the warranty property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWarranty() {
		return warranty;
	}

	/**
	 * Sets the value of the warranty property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWarranty(String value) {
		this.warranty = value;
	}

	/**
	 * Gets the value of the weeeTaxValue property.
	 * 
	 * @return possible object is {@link Price }
	 * 
	 */
	public Price getWEEETaxValue() {
		return weeeTaxValue;
	}

	/**
	 * Sets the value of the weeeTaxValue property.
	 * 
	 * @param value
	 *            allowed object is {@link Price }
	 * 
	 */
	public void setWEEETaxValue(Price value) {
		this.weeeTaxValue = value;
	}

}
