//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LowestOfferListingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LowestOfferListingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Qualifiers" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}QualifiersType"/>
 *         &lt;element name="NumberOfOfferListingsConsidered" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="SellerFeedbackCount" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="Price" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}PriceType"/>
 *         &lt;element name="MultipleOffersAtLowestPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LowestOfferListingType", propOrder = {
    "qualifiers",
    "numberOfOfferListingsConsidered",
    "sellerFeedbackCount",
    "price",
    "multipleOffersAtLowestPrice"
})
public class LowestOfferListingType {

    @XmlElement(name = "Qualifiers", required = true)
    protected QualifiersType qualifiers;
    @XmlElement(name = "NumberOfOfferListingsConsidered")
    protected BigInteger numberOfOfferListingsConsidered;
    @XmlElement(name = "SellerFeedbackCount", required = true)
    protected BigInteger sellerFeedbackCount;
    @XmlElement(name = "Price", required = true)
    protected PriceType price;
    @XmlElement(name = "MultipleOffersAtLowestPrice", required = true)
    protected String multipleOffersAtLowestPrice;

    /**
     * Gets the value of the qualifiers property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiersType }
     *     
     */
    public QualifiersType getQualifiers() {
        return qualifiers;
    }

    /**
     * Sets the value of the qualifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiersType }
     *     
     */
    public void setQualifiers(QualifiersType value) {
        this.qualifiers = value;
    }

    /**
     * Gets the value of the numberOfOfferListingsConsidered property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfOfferListingsConsidered() {
        return numberOfOfferListingsConsidered;
    }

    /**
     * Sets the value of the numberOfOfferListingsConsidered property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfOfferListingsConsidered(BigInteger value) {
        this.numberOfOfferListingsConsidered = value;
    }

    /**
     * Gets the value of the sellerFeedbackCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSellerFeedbackCount() {
        return sellerFeedbackCount;
    }

    /**
     * Sets the value of the sellerFeedbackCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSellerFeedbackCount(BigInteger value) {
        this.sellerFeedbackCount = value;
    }

    /**
     * Gets the value of the price property.
     * 
     * @return
     *     possible object is
     *     {@link PriceType }
     *     
     */
    public PriceType getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceType }
     *     
     */
    public void setPrice(PriceType value) {
        this.price = value;
    }

    /**
     * Gets the value of the multipleOffersAtLowestPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleOffersAtLowestPrice() {
        return multipleOffersAtLowestPrice;
    }

    /**
     * Sets the value of the multipleOffersAtLowestPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleOffersAtLowestPrice(String value) {
        this.multipleOffersAtLowestPrice = value;
    }

}
