//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.amazonaws.mws.myModel.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AttributeSet_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01", "AttributeSet");
    private final static QName _VariationChild_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd", "VariationChild");
    private final static QName _Identifiers_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01", "Identifiers");
    private final static QName _Product_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01", "Product");
    private final static QName _BaseRelationship_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01", "BaseRelationship");
    private final static QName _VariationParent_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01", "VariationParent");
    private final static QName _Products_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01", "Products");
    private final static QName _ItemAttributes_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd", "ItemAttributes");
    private final static QName _ListMatchingProductsResponse_QNAME = new QName("http://mws.amazonservices.com/schema/Products/2011-10-01", "ListMatchingProductsResponse");
    
    

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.amazonaws.mws.myModel.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForSKUResult }
     * 
     */
    public GetLowestPricedOffersForSKUResult createGetLowestPricedOffersForSKUResult() {
        return new GetLowestPricedOffersForSKUResult();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForSKUResult.Offers }
     * 
     */
    public GetLowestPricedOffersForSKUResult.Offers createGetLowestPricedOffersForSKUResultOffers() {
        return new GetLowestPricedOffersForSKUResult.Offers();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForSKUResult.Summary }
     * 
     */
    public GetLowestPricedOffersForSKUResult.Summary createGetLowestPricedOffersForSKUResultSummary() {
        return new GetLowestPricedOffersForSKUResult.Summary();
    }

    /**
     * Create an instance of {@link OfferCountType }
     * 
     */
    public OfferCountType createOfferCountType() {
        return new OfferCountType();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForASINResult }
     * 
     */
    public GetLowestPricedOffersForASINResult createGetLowestPricedOffersForASINResult() {
        return new GetLowestPricedOffersForASINResult();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForASINResult.Offers }
     * 
     */
    public GetLowestPricedOffersForASINResult.Offers createGetLowestPricedOffersForASINResultOffers() {
        return new GetLowestPricedOffersForASINResult.Offers();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForASINResult.Summary }
     * 
     */
    public GetLowestPricedOffersForASINResult.Summary createGetLowestPricedOffersForASINResultSummary() {
        return new GetLowestPricedOffersForASINResult.Summary();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link ItemAttributesType }
     * 
     */
    public ItemAttributesType createItemAttributesType() {
        return new ItemAttributesType();
    }

    /**
     * Create an instance of {@link AttributeSetType }
     * 
     */
    public AttributeSetType createAttributeSetType() {
        return new AttributeSetType();
    }

    /**
     * Create an instance of {@link VariationChildType }
     * 
     */
    public VariationChildType createVariationChildType() {
        return new VariationChildType();
    }

    /**
     * Create an instance of {@link BaseRelationshipType }
     * 
     */
    public BaseRelationshipType createBaseRelationshipType() {
        return new BaseRelationshipType();
    }

    /**
     * Create an instance of {@link NonNegativeIntegerWithUnits }
     * 
     */
    public NonNegativeIntegerWithUnits createNonNegativeIntegerWithUnits() {
        return new NonNegativeIntegerWithUnits();
    }

    /**
     * Create an instance of {@link DecimalWithUnits }
     * 
     */
    public DecimalWithUnits createDecimalWithUnits() {
        return new DecimalWithUnits();
    }

    /**
     * Create an instance of {@link DimensionType }
     * 
     */
    public DimensionType createDimensionType() {
        return new DimensionType();
    }

    /**
     * Create an instance of {@link CreatorType }
     * 
     */
    public CreatorType createCreatorType() {
        return new CreatorType();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link VariationParentType }
     * 
     */
    public VariationParentType createVariationParentType() {
        return new VariationParentType();
    }

    /**
     * Create an instance of {@link ProductList }
     * 
     */
    public ProductList createProductList() {
        return new ProductList();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link LowestPriceType }
     * 
     */
    public LowestPriceType createLowestPriceType() {
        return new LowestPriceType();
    }

    /**
     * Create an instance of {@link ShippingTimeType }
     * 
     */
    public ShippingTimeType createShippingTimeType() {
        return new ShippingTimeType();
    }

    /**
     * Create an instance of {@link SellerFeedbackType }
     * 
     */
    public SellerFeedbackType createSellerFeedbackType() {
        return new SellerFeedbackType();
    }

    /**
     * Create an instance of {@link AttributeSetList }
     * 
     */
    public AttributeSetList createAttributeSetList() {
        return new AttributeSetList();
    }

    /**
     * Create an instance of {@link BuyBoxPriceType }
     * 
     */
    public BuyBoxPriceType createBuyBoxPriceType() {
        return new BuyBoxPriceType();
    }

    /**
     * Create an instance of {@link OfferListingCountType }
     * 
     */
    public OfferListingCountType createOfferListingCountType() {
        return new OfferListingCountType();
    }

    /**
     * Create an instance of {@link SalesRankList }
     * 
     */
    public SalesRankList createSalesRankList() {
        return new SalesRankList();
    }

    /**
     * Create an instance of {@link MarketplaceASINType }
     * 
     */
    public MarketplaceASINType createMarketplaceASINType() {
        return new MarketplaceASINType();
    }

    /**
     * Create an instance of {@link NumberOfOfferListingsType }
     * 
     */
    public NumberOfOfferListingsType createNumberOfOfferListingsType() {
        return new NumberOfOfferListingsType();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersErrorType }
     * 
     */
    public GetLowestPricedOffersErrorType createGetLowestPricedOffersErrorType() {
        return new GetLowestPricedOffersErrorType();
    }

    /**
     * Create an instance of {@link OffersList }
     * 
     */
    public OffersList createOffersList() {
        return new OffersList();
    }

    /**
     * Create an instance of {@link OfferType }
     * 
     */
    public OfferType createOfferType() {
        return new OfferType();
    }

    /**
     * Create an instance of {@link CompetitivePriceType }
     * 
     */
    public CompetitivePriceType createCompetitivePriceType() {
        return new CompetitivePriceType();
    }

    /**
     * Create an instance of {@link MoneyType }
     * 
     */
    public MoneyType createMoneyType() {
        return new MoneyType();
    }

    /**
     * Create an instance of {@link RelationshipList }
     * 
     */
    public RelationshipList createRelationshipList() {
        return new RelationshipList();
    }

    /**
     * Create an instance of {@link LowestOfferListingList }
     * 
     */
    public LowestOfferListingList createLowestOfferListingList() {
        return new LowestOfferListingList();
    }

    /**
     * Create an instance of {@link LowestOfferListingType }
     * 
     */
    public LowestOfferListingType createLowestOfferListingType() {
        return new LowestOfferListingType();
    }

    /**
     * Create an instance of {@link CompetitivePriceList }
     * 
     */
    public CompetitivePriceList createCompetitivePriceList() {
        return new CompetitivePriceList();
    }

    /**
     * Create an instance of {@link ShipsFromType }
     * 
     */
    public ShipsFromType createShipsFromType() {
        return new ShipsFromType();
    }

    /**
     * Create an instance of {@link Points }
     * 
     */
    public Points createPoints() {
        return new Points();
    }

    /**
     * Create an instance of {@link DetailedShippingTimeType }
     * 
     */
    public DetailedShippingTimeType createDetailedShippingTimeType() {
        return new DetailedShippingTimeType();
    }

    /**
     * Create an instance of {@link CompetitivePricingType }
     * 
     */
    public CompetitivePricingType createCompetitivePricingType() {
        return new CompetitivePricingType();
    }

    /**
     * Create an instance of {@link QualifiersType }
     * 
     */
    public QualifiersType createQualifiersType() {
        return new QualifiersType();
    }

    /**
     * Create an instance of {@link PriceType }
     * 
     */
    public PriceType createPriceType() {
        return new PriceType();
    }

    /**
     * Create an instance of {@link SellerSKUIdentifier }
     * 
     */
    public SellerSKUIdentifier createSellerSKUIdentifier() {
        return new SellerSKUIdentifier();
    }

    /**
     * Create an instance of {@link SalesRankType }
     * 
     */
    public SalesRankType createSalesRankType() {
        return new SalesRankType();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForSKUResult.Identifier }
     * 
     */
    public GetLowestPricedOffersForSKUResult.Identifier createGetLowestPricedOffersForSKUResultIdentifier() {
        return new GetLowestPricedOffersForSKUResult.Identifier();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForSKUResult.Offers.Offer }
     * 
     */
    public GetLowestPricedOffersForSKUResult.Offers.Offer createGetLowestPricedOffersForSKUResultOffersOffer() {
        return new GetLowestPricedOffersForSKUResult.Offers.Offer();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForSKUResult.Summary.LowestPrices }
     * 
     */
    public GetLowestPricedOffersForSKUResult.Summary.LowestPrices createGetLowestPricedOffersForSKUResultSummaryLowestPrices() {
        return new GetLowestPricedOffersForSKUResult.Summary.LowestPrices();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForSKUResult.Summary.BuyBoxPrices }
     * 
     */
    public GetLowestPricedOffersForSKUResult.Summary.BuyBoxPrices createGetLowestPricedOffersForSKUResultSummaryBuyBoxPrices() {
        return new GetLowestPricedOffersForSKUResult.Summary.BuyBoxPrices();
    }

    /**
     * Create an instance of {@link OfferCountType.OfferCount }
     * 
     */
    public OfferCountType.OfferCount createOfferCountTypeOfferCount() {
        return new OfferCountType.OfferCount();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForASINResult.Identifier }
     * 
     */
    public GetLowestPricedOffersForASINResult.Identifier createGetLowestPricedOffersForASINResultIdentifier() {
        return new GetLowestPricedOffersForASINResult.Identifier();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForASINResult.Offers.Offer }
     * 
     */
    public GetLowestPricedOffersForASINResult.Offers.Offer createGetLowestPricedOffersForASINResultOffersOffer() {
        return new GetLowestPricedOffersForASINResult.Offers.Offer();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForASINResult.Summary.LowestPrices }
     * 
     */
    public GetLowestPricedOffersForASINResult.Summary.LowestPrices createGetLowestPricedOffersForASINResultSummaryLowestPrices() {
        return new GetLowestPricedOffersForASINResult.Summary.LowestPrices();
    }

    /**
     * Create an instance of {@link GetLowestPricedOffersForASINResult.Summary.BuyBoxPrices }
     * 
     */
    public GetLowestPricedOffersForASINResult.Summary.BuyBoxPrices createGetLowestPricedOffersForASINResultSummaryBuyBoxPrices() {
        return new GetLowestPricedOffersForASINResult.Summary.BuyBoxPrices();
    }

    /**
     * Create an instance of {@link LanguageType.Language }
     * 
     */
    public LanguageType.Language createLanguageTypeLanguage() {
        return new LanguageType.Language();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributeSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", name = "AttributeSet")
    public JAXBElement<AttributeSetType> createAttributeSet(AttributeSetType value) {
        return new JAXBElement<AttributeSetType>(_AttributeSet_QNAME, AttributeSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VariationChildType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd", name = "VariationChild", substitutionHeadNamespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", substitutionHeadName = "BaseRelationship")
    public JAXBElement<VariationChildType> createVariationChild(VariationChildType value) {
        return new JAXBElement<VariationChildType>(_VariationChild_QNAME, VariationChildType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", name = "Identifiers")
    public JAXBElement<IdentifierType> createIdentifiers(IdentifierType value) {
        return new JAXBElement<IdentifierType>(_Identifiers_QNAME, IdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", name = "Product")
    public JAXBElement<ProductType> createProduct(ProductType value) {
        return new JAXBElement<ProductType>(_Product_QNAME, ProductType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseRelationshipType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", name = "BaseRelationship")
    public JAXBElement<BaseRelationshipType> createBaseRelationship(BaseRelationshipType value) {
        return new JAXBElement<BaseRelationshipType>(_BaseRelationship_QNAME, BaseRelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VariationParentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", name = "VariationParent", substitutionHeadNamespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", substitutionHeadName = "BaseRelationship")
    public JAXBElement<VariationParentType> createVariationParent(VariationParentType value) {
        return new JAXBElement<VariationParentType>(_VariationParent_QNAME, VariationParentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductList }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", name = "Products")
    public JAXBElement<ProductList> createProducts(ProductList value) {
        return new JAXBElement<ProductList>(_Products_QNAME, ProductList.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemAttributesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01/default.xsd", name = "ItemAttributes", substitutionHeadNamespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", substitutionHeadName = "AttributeSet")
    public JAXBElement<ItemAttributesType> createItemAttributes(ItemAttributesType value) {
        return new JAXBElement<ItemAttributesType>(_ItemAttributes_QNAME, ItemAttributesType.class, null, value);
    }
    
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListMatchingProductsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://mws.amazonservices.com/schema/Products/2011-10-01", name = "ListMatchingProductsResponse")
    public JAXBElement<ListMatchingProductsResponse> createListMatchingProductsResponse(ListMatchingProductsResponse value) {
        return new JAXBElement<ListMatchingProductsResponse>(_ListMatchingProductsResponse_QNAME, ListMatchingProductsResponse.class, null, value);
    }

}
