//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for OfferCountType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfferCountType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OfferCount" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                 &lt;attribute name="condition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fulfillmentChannel" use="required" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}FulfillmentChannelType" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfferCountType", propOrder = {
    "offerCount"
})
public class OfferCountType {

    @XmlElement(name = "OfferCount")
    protected List<OfferCountType.OfferCount> offerCount;

    /**
     * Gets the value of the offerCount property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offerCount property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOfferCount().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OfferCountType.OfferCount }
     * 
     * 
     */
    public List<OfferCountType.OfferCount> getOfferCount() {
        if (offerCount == null) {
            offerCount = new ArrayList<OfferCountType.OfferCount>();
        }
        return this.offerCount;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
     *       &lt;attribute name="condition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fulfillmentChannel" use="required" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}FulfillmentChannelType" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class OfferCount {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "condition", required = true)
        protected String condition;
        @XmlAttribute(name = "fulfillmentChannel", required = true)
        protected FulfillmentChannelType fulfillmentChannel;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the condition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCondition() {
            return condition;
        }

        /**
         * Sets the value of the condition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCondition(String value) {
            this.condition = value;
        }

        /**
         * Gets the value of the fulfillmentChannel property.
         * 
         * @return
         *     possible object is
         *     {@link FulfillmentChannelType }
         *     
         */
        public FulfillmentChannelType getFulfillmentChannel() {
            return fulfillmentChannel;
        }

        /**
         * Sets the value of the fulfillmentChannel property.
         * 
         * @param value
         *     allowed object is
         *     {@link FulfillmentChannelType }
         *     
         */
        public void setFulfillmentChannel(FulfillmentChannelType value) {
            this.fulfillmentChannel = value;
        }

    }

}
