//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://mws.amazonservices.com/schema/Products/2011-10-01}Identifiers"/>
 *         &lt;element name="AttributeSets" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}AttributeSetList" minOccurs="0"/>
 *         &lt;element name="Relationships" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}RelationshipList" minOccurs="0"/>
 *         &lt;element name="CompetitivePricing" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}CompetitivePricingType" minOccurs="0"/>
 *         &lt;element name="SalesRankings" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}SalesRankList" minOccurs="0"/>
 *         &lt;element name="LowestOfferListings" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}LowestOfferListingList" minOccurs="0"/>
 *         &lt;element name="Offers" type="{http://mws.amazonservices.com/schema/Products/2011-10-01}OffersList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductType", propOrder = {
    "identifiers",
    "attributeSets",
    "relationships",
    "competitivePricing",
    "salesRankings",
    "lowestOfferListings",
    "offers"
})
public class ProductType {

    @XmlElement(name = "Identifiers", required = true)
    protected IdentifierType identifiers;
    @XmlElement(name = "AttributeSets")
    protected AttributeSetList attributeSets;
    @XmlElement(name = "Relationships")
    protected RelationshipList relationships;
    @XmlElement(name = "CompetitivePricing")
    protected CompetitivePricingType competitivePricing;
    @XmlElement(name = "SalesRankings")
    protected SalesRankList salesRankings;
    @XmlElement(name = "LowestOfferListings")
    protected LowestOfferListingList lowestOfferListings;
    @XmlElement(name = "Offers")
    protected OffersList offers;

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setIdentifiers(IdentifierType value) {
        this.identifiers = value;
    }

    /**
     * Gets the value of the attributeSets property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSetList }
     *     
     */
    public AttributeSetList getAttributeSets() {
        return attributeSets;
    }

    /**
     * Sets the value of the attributeSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSetList }
     *     
     */
    public void setAttributeSets(AttributeSetList value) {
        this.attributeSets = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link RelationshipList }
     *     
     */
    public RelationshipList getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelationshipList }
     *     
     */
    public void setRelationships(RelationshipList value) {
        this.relationships = value;
    }

    /**
     * Gets the value of the competitivePricing property.
     * 
     * @return
     *     possible object is
     *     {@link CompetitivePricingType }
     *     
     */
    public CompetitivePricingType getCompetitivePricing() {
        return competitivePricing;
    }

    /**
     * Sets the value of the competitivePricing property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetitivePricingType }
     *     
     */
    public void setCompetitivePricing(CompetitivePricingType value) {
        this.competitivePricing = value;
    }

    /**
     * Gets the value of the salesRankings property.
     * 
     * @return
     *     possible object is
     *     {@link SalesRankList }
     *     
     */
    public SalesRankList getSalesRankings() {
        return salesRankings;
    }

    /**
     * Sets the value of the salesRankings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesRankList }
     *     
     */
    public void setSalesRankings(SalesRankList value) {
        this.salesRankings = value;
    }

    /**
     * Gets the value of the lowestOfferListings property.
     * 
     * @return
     *     possible object is
     *     {@link LowestOfferListingList }
     *     
     */
    public LowestOfferListingList getLowestOfferListings() {
        return lowestOfferListings;
    }

    /**
     * Sets the value of the lowestOfferListings property.
     * 
     * @param value
     *     allowed object is
     *     {@link LowestOfferListingList }
     *     
     */
    public void setLowestOfferListings(LowestOfferListingList value) {
        this.lowestOfferListings = value;
    }

    /**
     * Gets the value of the offers property.
     * 
     * @return
     *     possible object is
     *     {@link OffersList }
     *     
     */
    public OffersList getOffers() {
        return offers;
    }

    /**
     * Sets the value of the offers property.
     * 
     * @param value
     *     allowed object is
     *     {@link OffersList }
     *     
     */
    public void setOffers(OffersList value) {
        this.offers = value;
    }

}
