//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.29 at 10:08:35 PM GMT+08:00 
//


package com.amazonaws.mws.model.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SellerFeedbackType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SellerFeedbackType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SellerPositiveFeedbackRating" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="FeedbackCount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SellerFeedbackType", propOrder = {
    "sellerPositiveFeedbackRating",
    "feedbackCount"
})
public class SellerFeedbackType {

    @XmlElement(name = "SellerPositiveFeedbackRating")
    protected Double sellerPositiveFeedbackRating;
    @XmlElement(name = "FeedbackCount")
    protected long feedbackCount;

    /**
     * Gets the value of the sellerPositiveFeedbackRating property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSellerPositiveFeedbackRating() {
        return sellerPositiveFeedbackRating;
    }

    /**
     * Sets the value of the sellerPositiveFeedbackRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSellerPositiveFeedbackRating(Double value) {
        this.sellerPositiveFeedbackRating = value;
    }

    /**
     * Gets the value of the feedbackCount property.
     * 
     */
    public long getFeedbackCount() {
        return feedbackCount;
    }

    /**
     * Sets the value of the feedbackCount property.
     * 
     */
    public void setFeedbackCount(long value) {
        this.feedbackCount = value;
    }

}
